# Called by the apps, in the deploy.yaml of their own repositories.

# This pipeline uses the following Github Secrets:
# FEDERATED_CLIENT_ID: clientid of AadClient for ArgoCD IngressGate, set in the github environment.
# GITOPS_SSH_KEY: private key of gitops repository's depkey

name: Testing
on:
  release:
    types: [published]
  push:
    branches:
      - "feature**"
  workflow_dispatch:

jobs:

  preps:
    # Its outputs are needed for the next job, so need to be in its own job.
    name: Preps
    runs-on: ubuntu-latest

    steps:
      - name: Determine deployment variables
        # Initially meant to get the target environment, but as it is easier to manipulate strings in bash than in gha, a few useful
        # outputs have been added.
        id: environment
        run: |

          echo "${{github}}"

          case "${{github.ref_name}}" in
            main|master|hotfix*)
              echo "WE ARE MAIN"
            release|acceptance|patch*)
              echo "WE ARE ACC"
            *)
              echo "WE ARE DEV"
          esac
